name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v5

    - name: Install pandoc
      uses: pandoc/actions/setup@v1

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Install pre-commit
      run: pip install pre-commit

    - name: Run pre-commit
      run: pre-commit run --all-files

  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v5

    - name: Install Neovim
      uses: rhysd/action-setup-vim@v1
      with:
        neovim: true
        version: stable

    - name: Install plenary.nvim
      run: |
        mkdir -p ~/.local/share/nvim/site/pack/vendor/start
        git clone --depth 1 https://github.com/nvim-lua/plenary.nvim \
          ~/.local/share/nvim/site/pack/vendor/start/plenary.nvim

    - name: Run tests
      run: |
        nvim --version
        nvim --headless -c "PlenaryBustedDirectory tests/ {minimal_init = 'tests/minimal_init.lua'}"
